build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bullseye
  amd64: ghcr.io/home-assistant/amd64-base-debian:bullseye
  armhf: ghcr.io/home-assistant/armhf-base-debian:bullseye
  armv7: ghcr.io/home-assistant/armv7-base-debian:bullseye
  i386: ghcr.io/home-assistant/i386-base-debian:bullseye
squash: false
labels:
  io.hass.type: addon
  io.hass.version: "4.0.0"
  io.hass.arch: "armhf|armv7|aarch64|amd64|i386"
args:
  TEMPIO_VERSION: "2021.09.0" 