name: "FamilyStream"
description: "Stream music from FamilyStream to Home Assistant media players"
version: "1.1.0"
slug: "familystream"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:music
options:
  default_media_player: ""
schema:
  default_media_player: str
webui: "http://[HOST]:[PORT:8099]"
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web interface (Not required for Ingress)" 