name: "FamilyStream Firefox Kiosk"
description: "FamilyStream in Firefox kiosk mode with audio forwarding to Home Assistant media players"
version: "4.0.0"
slug: "familystream_firefox"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:music
hassio_api: true
auth_api: true
homeassistant_api: true
host_network: true
audio: true
devices:
  - /dev/snd
options:
  default_media_player: ""
  supervisor_token: ""
schema:
  default_media_player: str
  supervisor_token: str
webui: "http://[HOST]:[PORT:8099]"
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web interface (Not required for Ingress)" 