name: "Firefox with Audio Streaming"
description: "Firefox browser with audio streaming to Home Assistant media player"
version: "5.0.0"
slug: "firefox_audio_streaming"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
hassio_role: "default"
webui: "http://[HOST]:[PORT:5800]"
ports:
  5800/tcp: 5800
  5900/tcp: 5900
ports_description:
  5800/tcp: "Web interface (Not required for Ingress)"
  5900/tcp: "VNC connection (Not required for Ingress)"
ingress: true
ingress_port: 5800
panel_icon: "mdi:firefox"
panel_title: "Firefox Media"
options:
  media_player: ""
schema:
  media_player: "str" 